# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
android.useAndroidX=true

android.enableJetifier=false

# Give Gradle more memory for FTC SDK, OpenCV, AprilTag and asset packaging
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8

android.nonTransitiveRClass=false